### ISSUE TITLE
age: '.gpg' file extension is shown in output

### ISSUE THREAD

**Issue by mattmartini** [skx/pass#4]
When performing `pass age`, the output shows the file extensions, `.gpg`

This is unnecessary and distracting.

```
$ pass age
31 seconds ago Bank/piggy.gpg
31 seconds ago Mail/Gmail.gpg
31 seconds ago Mail/Yahoo.gpg
31 seconds ago News/CNN.gpg
31 seconds ago News/NYTimes.gpg
31 seconds ago Shop/Amazon.gpg
31 seconds ago Shop/Ebay.gpg
31 seconds ago Shop/Etsy.gpg

```

A pull request to address this is forthcoming to make the output like:

```
$ pass age
3 minutes ago Bank/piggy
3 minutes ago Mail/Gmail
3 minutes ago Mail/Yahoo
3 minutes ago News/CNN
3 minutes ago News/NYTimes
3 minutes ago Shop/Amazon
3 minutes ago Shop/Ebay
3 minutes ago Shop/Etsy
```

**Comment by skx** [comment]
You know I never really noticed that, but now you mention it as an issue, removing it makes complete sense!

Thanks for taking the time to report, and fix.
